### ISSUE TITLE
Synchronizing Amazon S3 to Amazon S3

### ISSUE THREAD

**Issue by jackhuang89** [arkadedigital/magento2-s3#12]
after the last step of installation by command line:

php /path/to/magento/bin/magento s3:storage:sync --enable

Use web interface go to admin panel

<img width="961" alt="screen shot 2016-04-22 at 5 53 04 pm" src="https://cloud.githubusercontent.com/assets/3734296/14738300/57b61444-08b3-11e6-8140-2f069fa7d249.png">

the config value is not S3 after the command.
When trying to click  "Synchronize" button.

It show me this
<img width="1301" alt="screen shot 2016-04-22 at 5 56 03 pm" src="https://cloud.githubusercontent.com/assets/3734296/14738344/9cab90ba-08b3-11e6-8e77-5111b2890f18.png">

Anyway, the image still have upload to S3.
But the "System messages" keep telling me 
"We were unable to synchronize one or more media files. Please refer to the log file for details."

**Comment by thaiphan** [comment]
Hey @jackhuang89,

I've found that the whole default backend for that page is a bit a mess to be honest! That's why I built the CLI command.

There's a table in the database called "flag". If you set the state for the sync to be 0, then that message will go away. I also recommend flushing your cache!

Regards,

Thai

**Comment by jackhuang89** [comment]
Ok man. Just set it 0.
